version: "3.8"

services:
  mongo:
    image: mongo:8.0.9
    container_name: salary-split-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: salary-split-api-dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev  # for development
    container_name: salary-split-api-dev
    ports:
      - "5300:5300"
    environment:
      - NODE_ENV=development
      - PORT=5300
      - MONGO_URI=mongodb://mongo:27017/salary-split-api-dev
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - CORS_ORIGIN_NETWORK=${CORS_ORIGIN_NETWORK}
      - JWT_SECRET=${JWT_SECRET} 
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET} 
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} 
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} 

    volumes:
      - .:/usr/src/app # Mount code for hot reloading
      - /usr/src/app/node_modules # Avoids overwriting node_modules in container
    command: nodemon --watch src --exec ts-node src/server.ts
    depends_on:
      - mongo

volumes:
  mongo_data:
