# <REPO_NAME> is the name of the repo, eg salary-split-api
# <DOMAIN> is the domain of the website, eg api.salarysplit.co.uk
# <PORT> is the port number of the website, eg 5300

name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  workflow_dispatch:

# Add environment variables at workflow level
env:
  DOCKER_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/salary-split-api
  DOMAIN: api.salarysplit.co.uk

jobs:
  # Add a build-and-push job that runs first
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tag current production as previous
        continue-on-error: true # Allow this step to fail on first deployment
        run: |
          if docker pull ${{ env.DOCKER_IMAGE }}:latest; then
            echo "Previous version exists, creating backup tag"
            docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:previous
            docker push ${{ env.DOCKER_IMAGE }}:previous
          else
            echo "No previous version found, skipping backup"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        timeout-minutes: 15

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production_environment
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Nginx configuration
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "nginx/salary-split-api.conf"
          target: "/home/${{ secrets.DO_USERNAME }}/nginx/"
          strip_components: 1

      - name: Configure Nginx and SSL
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script_stop: true
          script: |
            echo "Starting nginx configuration..."

            # Debug: Show current directory and contents
            pwd
            ls -la /home/${{ secrets.DO_USERNAME }}/nginx/

            # Check existing configuration
            if [ -f "/etc/nginx/sites-available/api.salarysplit.co.uk" ]; then
              echo "Checking existing nginx configuration..."
              if grep -q "ssl_certificate" "/etc/nginx/sites-available/api.salarysplit.co.uk"; then
                echo "SSL configuration exists, preserving current nginx config"
                exit 0
              fi
            fi

            echo "Setting up new nginx config..."
            if [ ! -f "/home/${{ secrets.DO_USERNAME }}/nginx/salary-split-api.conf" ]; then
              echo "Error: nginx configuration file not found"
              exit 1
            fi

            # Move configuration file
            sudo mv "/home/${{ secrets.DO_USERNAME }}/nginx/salary-split-api.conf" "/etc/nginx/sites-available/api.salarysplit.co.uk"
            sudo ln -sf "/etc/nginx/sites-available/api.salarysplit.co.uk" "/etc/nginx/sites-enabled/"

            # Verify nginx configuration
            echo "Testing nginx configuration..."
            sudo nginx -t

            # Setup SSL if needed
            if [ ! -f "/etc/letsencrypt/live/api.salarysplit.co.uk/fullchain.pem" ]; then
              echo "Setting up SSL certificate..."
              sudo certbot --nginx -d api.salarysplit.co.uk \
                -d api.salarysplit.co.uk \
                --non-interactive \
                --agree-tos \
                --email ${{ secrets.CERTBOT_EMAIL }} \
                --redirect
            fi

            echo "Reloading nginx..."
            sudo systemctl reload nginx

      - name: Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script_stop: true
          script: |
            # Deploy Docker container
            echo "Deploying Docker container..."

            echo "Cleaning up existing containers..."
            docker stop salary-split-api salary-split-api-new || true
            docker rm salary-split-api salary-split-api-new || true

            echo "Pulling latest image..."
            docker pull ${{ env.DOCKER_IMAGE }}:latest

            echo "Starting new container..."
            docker run -d \
              --name salary-split-api-new \
              --restart unless-stopped \
              --health-cmd="curl -f http://localhost:5300/ || exit 1" \
              --health-interval=30s \
              --health-timeout=5s \
              --health-retries=3 \
              -p 5300:5300 \
              -e NODE_ENV=production \
              -e PORT=5300 \
              -e MONGO_URI='${{ secrets.MONGO_URI }}' \
              -e CORS_ORIGIN='${{ secrets.CORS_ORIGIN }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -e ACCESS_TOKEN_SECRET='${{ secrets.ACCESS_TOKEN_SECRET }}' \
              -e REFRESH_TOKEN_SECRET='${{ secrets.REFRESH_TOKEN_SECRET }}' \
              ${{ env.DOCKER_IMAGE }}:latest

            sleep 15

            if ! docker ps | grep -q "salary-split-api-new"; then
              echo "Container failed to start"
              docker logs salary-split-api-new
              exit 1
            fi

      - name: Health Check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script_stop: true
          script: |
            HEALTH_CHECK_ATTEMPTS=0
            MAX_ATTEMPTS=10

            until [ $HEALTH_CHECK_ATTEMPTS -eq $MAX_ATTEMPTS ] || curl -sf http://localhost:5300 > /dev/null; do
              echo "Attempt $((HEALTH_CHECK_ATTEMPTS + 1))/$MAX_ATTEMPTS"
              HEALTH_CHECK_ATTEMPTS=$((HEALTH_CHECK_ATTEMPTS + 1))
              sleep 3
            done

            if [ $HEALTH_CHECK_ATTEMPTS -eq $MAX_ATTEMPTS ]; then
              echo "Health check failed"
              docker logs salary-split-api-new
              exit 1
            fi

            echo "Container healthy, finalizing deployment..."
            docker stop salary-split-api || true
            docker rm salary-split-api || true
            docker rename salary-split-api-new salary-split-api

  # Best practice: Keep the rollback job
  rollback:
    needs: [build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${DOCKER_IMAGE}:previous
            docker stop salary-split-api || true
            docker rm salary-split-api || true

            docker run -d \
              --name salary-split-api \
              --restart unless-stopped \
              -p 5300:5300 \
              -e NODE_ENV=production \
              -e MONGO_URI='${{ secrets.MONGO_URI }}' \
              -e CORS_ORIGIN='${{ secrets.CORS_ORIGIN }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -e ACCESS_TOKEN_SECRET='${{ secrets.ACCESS_TOKEN_SECRET }}' \
              -e REFRESH_TOKEN_SECRET='${{ secrets.REFRESH_TOKEN_SECRET }}' \
              ${DOCKER_IMAGE}:previous

            echo "Rollback completed"
